project:
  type: website
  output-dir: docs

website:
  title: "WorldRegio"
  navbar:
    left:
      - href: index.qmd
        text: "Claude Grasland"
      - about.qmd
      - links.qmd

format:
  html:
    theme: 
      dark: solar
      light: minty
    css: styles.css
    toc: true



